"""Pseudo-labelling: can unlabelled test rows be used as extra training data?

Adversarial validation shows train and test are indistinguishable (AUC ~0.48),
so test molecules are in-distribution and their predicted labels are plausible
training signal. `egc` is the case that matters: 2,028 labelled rows carrying
half the metric, with 1,352 unlabelled test rows available (+67%).

Honest evaluation is the whole difficulty. Pseudo-labels generated by a model
trained on ALL training rows leak into every validation fold. So for each fold
we generate pseudo-labels using ONLY that fold's training split, then retrain on
(fold-train + pseudo-labelled test) and score the untouched validation fold.
Slower, but it is the only way the number means anything.
"""
import argparse

import numpy as np

from . import config as C
from . import cv, features, models
from .data import load_raw, subset

BLOCKS = ["desc_raw", "desc_cap", "morgan2", "maccs", "avalon", "polymer", "decomp_bb"]


def run(target, model_name="lgbm", n_folds=10, weight=1.0, seed=C.SEED):
    tr, te = load_raw()
    X_all = features.select(features.build(), BLOCKS)
    tr_t, te_t = subset(tr, target), subset(te, target)
    X = features.for_rows(tr_t, X_all).values.astype(np.float32)
    Xte = features.for_rows(te_t, X_all).values.astype(np.float32)
    y = tr_t.target.values

    oof_base = np.zeros(len(y))
    oof_pseudo = np.zeros(len(y))

    for tr_i, va_i in cv.make_folds(len(y), n_splits=n_folds, seed=seed):
        # 1. baseline model on this fold's training split
        m = models.make(model_name, seed=seed)()
        m.fit_fold(X[tr_i], y[tr_i], X[va_i], y[va_i])
        oof_base[va_i] = m.predict(X[va_i])

        # 2. pseudo-label the test rows using ONLY this fold's model
        pseudo_y = m.predict(Xte)

        # 3. retrain on real + pseudo, score the untouched validation fold
        X_aug = np.vstack([X[tr_i], Xte])
        y_aug = np.concatenate([y[tr_i], pseudo_y])
        w = np.concatenate([np.ones(len(tr_i)), np.full(len(Xte), weight)])
        m2 = models.make(model_name, seed=seed)()
        try:
            m2.m.fit(X_aug, y_aug, sample_weight=w, eval_set=[(X[va_i], y[va_i])],
                     eval_metric="rmse",
                     callbacks=[__import__("lightgbm").early_stopping(200, verbose=False)])
        except TypeError:
            m2.fit_fold(X_aug, y_aug, X[va_i], y[va_i])
        oof_pseudo[va_i] = m2.predict(X[va_i])

    b = cv.score(y, oof_base)["r2"]
    p = cv.score(y, oof_pseudo)["r2"]
    print(f"  {target:4s} baseline={b:.4f}  pseudo(w={weight})={p:.4f}  delta={p-b:+.4f}"
          f"  {'HELPS' if p-b > 0.001 else 'no gain'}")
    return b, p


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--model", default="lgbm")
    ap.add_argument("--folds", type=int, default=10)
    ap.add_argument("--weights", type=float, nargs="+", default=[0.3, 1.0])
    a = ap.parse_args()
    for w in a.weights:
        print(f"=== pseudo-labelling, test-row weight {w} ===")
        for t in C.TARGET_TYPES:
            run(t, a.model, a.folds, weight=w)
